package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class ActivityType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.activity_type_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer activityTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.activity_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String activityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.activity_type_id
     *
     * @return the value of activity_type.activity_type_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getActivityTypeId() {
        return activityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.activity_type_id
     *
     * @param activityTypeId the value for activity_type.activity_type_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setActivityTypeId(Integer activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.activity_type
     *
     * @return the value of activity_type.activity_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.activity_type
     *
     * @param activityType the value for activity_type.activity_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setActivityType(String activityType) {
        this.activityType = activityType == null ? null : activityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.delete_flag
     *
     * @return the value of activity_type.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.delete_flag
     *
     * @param deleteFlag the value for activity_type.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.create_time
     *
     * @return the value of activity_type.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.create_time
     *
     * @param createTime the value for activity_type.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}