package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.product_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.full_money
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer fullMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.reduce_money
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer reduceMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.product_id
     *
     * @return the value of activity.product_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.product_id
     *
     * @param productId the value for activity.product_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.discount
     *
     * @return the value of activity.discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.discount
     *
     * @param discount the value for activity.discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.full_money
     *
     * @return the value of activity.full_money
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getFullMoney() {
        return fullMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.full_money
     *
     * @param fullMoney the value for activity.full_money
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setFullMoney(Integer fullMoney) {
        this.fullMoney = fullMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.reduce_money
     *
     * @return the value of activity.reduce_money
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getReduceMoney() {
        return reduceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.reduce_money
     *
     * @param reduceMoney the value for activity.reduce_money
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setReduceMoney(Integer reduceMoney) {
        this.reduceMoney = reduceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.delete_flag
     *
     * @return the value of activity.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.delete_flag
     *
     * @param deleteFlag the value for activity.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}