package com.mbp.entity;

import java.io.Serializable;

public class ActivityDiscountProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_discount_product.produc_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer producId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_discount_product.activity_discount_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer activityDiscountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_discount_product
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_discount_product.produc_id
     *
     * @return the value of activity_discount_product.produc_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getProducId() {
        return producId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_discount_product.produc_id
     *
     * @param producId the value for activity_discount_product.produc_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProducId(Integer producId) {
        this.producId = producId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_discount_product.activity_discount_id
     *
     * @return the value of activity_discount_product.activity_discount_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getActivityDiscountId() {
        return activityDiscountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_discount_product.activity_discount_id
     *
     * @param activityDiscountId the value for activity_discount_product.activity_discount_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setActivityDiscountId(Integer activityDiscountId) {
        this.activityDiscountId = activityDiscountId;
    }
}