package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class Color implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column color.color_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer colorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column color.color_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String colorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column color.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table color
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column color.color_id
     *
     * @return the value of color.color_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column color.color_id
     *
     * @param colorId the value for color.color_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setColorId(Integer colorId) {
        this.colorId = colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column color.color_name
     *
     * @return the value of color.color_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getColorName() {
        return colorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column color.color_name
     *
     * @param colorName the value for color.color_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setColorName(String colorName) {
        this.colorName = colorName == null ? null : colorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column color.create_time
     *
     * @return the value of color.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column color.create_time
     *
     * @param createTime the value for color.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}