package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class Model implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.model_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String modelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.brand_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_id
     *
     * @return the value of model.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_id
     *
     * @param modelId the value for model.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.model_type
     *
     * @return the value of model.model_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.model_type
     *
     * @param modelType the value for model.model_type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setModelType(String modelType) {
        this.modelType = modelType == null ? null : modelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.brand_id
     *
     * @return the value of model.brand_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.brand_id
     *
     * @param brandId the value for model.brand_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.delete_flag
     *
     * @return the value of model.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.delete_flag
     *
     * @param deleteFlag the value for model.delete_flag
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.create_time
     *
     * @return the value of model.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.create_time
     *
     * @param createTime the value for model.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}