package com.mbp.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_number
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.person_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.address_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_status
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.actual_amount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private BigDecimal actualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.activity_amount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private BigDecimal activityAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_table
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_number
     *
     * @return the value of order_table.order_number
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_number
     *
     * @param orderNumber the value for order_table.order_number
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.person_id
     *
     * @return the value of order_table.person_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.person_id
     *
     * @param personId the value for order_table.person_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.address_id
     *
     * @return the value of order_table.address_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.address_id
     *
     * @param addressId the value for order_table.address_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_status
     *
     * @return the value of order_table.order_status
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_status
     *
     * @param orderStatus the value for order_table.order_status
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.actual_amount
     *
     * @return the value of order_table.actual_amount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.actual_amount
     *
     * @param actualAmount the value for order_table.actual_amount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.activity_amount
     *
     * @return the value of order_table.activity_amount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public BigDecimal getActivityAmount() {
        return activityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.activity_amount
     *
     * @param activityAmount the value for order_table.activity_amount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setActivityAmount(BigDecimal activityAmount) {
        this.activityAmount = activityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.create_time
     *
     * @return the value of order_table.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.create_time
     *
     * @param createTime the value for order_table.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}