package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class PersonAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_account.person_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_account.telephone
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_account.password
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_account.type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_account.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_account.person_id
     *
     * @return the value of person_account.person_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_account.person_id
     *
     * @param personId the value for person_account.person_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_account.telephone
     *
     * @return the value of person_account.telephone
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_account.telephone
     *
     * @param telephone the value for person_account.telephone
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_account.password
     *
     * @return the value of person_account.password
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_account.password
     *
     * @param password the value for person_account.password
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_account.type
     *
     * @return the value of person_account.type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_account.type
     *
     * @param type the value for person_account.type
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_account.create_time
     *
     * @return the value of person_account.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_account.create_time
     *
     * @param createTime the value for person_account.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "PersonAccount{" +
                "personId=" + personId +
                ", telephone='" + telephone + '\'' +
                ", password='" + password + '\'' +
                ", type=" + type +
                ", createTime=" + createTime +
                '}';
    }
}