package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class ProductInfo implements Serializable {

    private Integer productId;
    private String productName;
    private Integer modelId;
    private String productImage;
    private String productInfo;
    private Integer productStatus;
    private Integer productSaleNum;
    private Date createTime;
    private static final long serialVersionUID = 1L;

    //映射关系
    //机型
    private Model model;
    //价格
    private Stock stock;
    //商品活动
    private ActivityDiscountProduct activityDiscountProduct;
    private ActivityReduceProduct activityReduceProduct;


    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    public Stock getStock() {
        return stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }

    public ActivityDiscountProduct getActivityDiscountProduct() {
        return activityDiscountProduct;
    }

    public void setActivityDiscountProduct(ActivityDiscountProduct activityDiscountProduct) {
        this.activityDiscountProduct = activityDiscountProduct;
    }

    public ActivityReduceProduct getActivityReduceProduct() {
        return activityReduceProduct;
    }

    public void setActivityReduceProduct(ActivityReduceProduct activityReduceProduct) {
        this.activityReduceProduct = activityReduceProduct;
    }

    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.model_id
     *
     * @return the value of product_info.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.model_id
     *
     * @param modelId the value for product_info.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_image
     *
     * @return the value of product_info.product_image
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_image
     *
     * @param productImage the value for product_info.product_image
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_info
     *
     * @return the value of product_info.product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getProductInfo() {
        return productInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_info
     *
     * @param productInfo the value for product_info.product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductInfo(String productInfo) {
        this.productInfo = productInfo == null ? null : productInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_status
     *
     * @return the value of product_info.product_status
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_status
     *
     * @param productStatus the value for product_info.product_status
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_sale_num
     *
     * @return the value of product_info.product_sale_num
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getProductSaleNum() {
        return productSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_sale_num
     *
     * @param productSaleNum the value for product_info.product_sale_num
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductSaleNum(Integer productSaleNum) {
        this.productSaleNum = productSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "ProductInfo{" +
                "productId=" + productId +
                ", productName='" + productName + '\'' +
                ", modelId=" + modelId +
                ", productImage='" + productImage + '\'' +
                ", productInfo='" + productInfo + '\'' +
                ", productStatus=" + productStatus +
                ", productSaleNum=" + productSaleNum +
                ", createTime=" + createTime +
                ", model=" + model +
                ", stock=" + stock +
                ", activityDiscountProduct=" + activityDiscountProduct +
                ", activityReduceProduct=" + activityReduceProduct +
                '}';
    }
}