package com.mbp.entity;

import java.io.Serializable;
import java.util.Date;

public class Standard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.standard_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer standardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.standard_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private String standardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.standard_id
     *
     * @return the value of standard.standard_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.standard_id
     *
     * @param standardId the value for standard.standard_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.standard_name
     *
     * @return the value of standard.standard_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public String getStandardName() {
        return standardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.standard_name
     *
     * @param standardName the value for standard.standard_name
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setStandardName(String standardName) {
        this.standardName = standardName == null ? null : standardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.create_time
     *
     * @return the value of standard.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.create_time
     *
     * @param createTime the value for standard.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}