package com.mbp.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Stock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_number
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer stockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.color_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer colorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.store_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.product_price
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_number
     *
     * @return the value of stock.stock_number
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getStockNumber() {
        return stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_number
     *
     * @param stockNumber the value for stock.stock_number
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setStockNumber(Integer stockNumber) {
        this.stockNumber = stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.model_id
     *
     * @return the value of stock.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.model_id
     *
     * @param modelId the value for stock.model_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.color_id
     *
     * @return the value of stock.color_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.color_id
     *
     * @param colorId the value for stock.color_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setColorId(Integer colorId) {
        this.colorId = colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.store_id
     *
     * @return the value of stock.store_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.store_id
     *
     * @param storeId the value for stock.store_id
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.product_price
     *
     * @return the value of stock.product_price
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.product_price
     *
     * @param productPrice the value for stock.product_price
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.create_time
     *
     * @return the value of stock.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.create_time
     *
     * @param createTime the value for stock.create_time
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}