package com.mbp.dao;

import com.mbp.entity.ActivityReduceProduct;

public interface ActivityReduceProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce_product
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(ActivityReduceProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce_product
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(ActivityReduceProduct record);
}