package com.mbp.dao;

import com.mbp.entity.ActivityDiscount;

public interface ActivityDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int deleteByPrimaryKey(Integer activityDiscountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(ActivityDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(ActivityDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    ActivityDiscount selectByPrimaryKey(Integer activityDiscountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKey(ActivityDiscount record);
}