package com.mbp.dao;

import com.mbp.entity.ActivityReduce;

public interface ActivityReduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int deleteByPrimaryKey(Integer activityReduceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(ActivityReduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(ActivityReduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    ActivityReduce selectByPrimaryKey(Integer activityReduceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityReduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_reduce
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKey(ActivityReduce record);
}