package com.mbp.dao;

import com.mbp.entity.ActivityDiscountProduct;

public interface ActivityDiscountProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount_product
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(ActivityDiscountProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_discount_product
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(ActivityDiscountProduct record);
}