package com.mbp.dao;

import com.mbp.entity.OrderShopCart;

public interface OrderShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop_cart
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(OrderShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shop_cart
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(OrderShopCart record);
}