package com.mbp.dao;

import com.mbp.entity.PersonCollect;

public interface PersonCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_collect
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(PersonCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_collect
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(PersonCollect record);
}