package com.mbp.dao;

import entity.PersonInfo;

public interface PersonInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 16:30:03 CST 2019
     */
    int deleteByPrimaryKey(Integer personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 16:30:03 CST 2019
     */
    int insert(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 16:30:03 CST 2019
     */
    int insertSelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 16:30:03 CST 2019
     */
    PersonInfo selectByPrimaryKey(Integer personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 16:30:03 CST 2019
     */
    int updateByPrimaryKeySelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 16:30:03 CST 2019
     */
    int updateByPrimaryKey(PersonInfo record);
}