package com.mbp.dao;

import com.mbp.entity.ProductInfo;

import java.util.List;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    ProductInfo selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKey(ProductInfo record);

    /**
     * 查询热销手机单品
     * @return ProductInfo
     */
    List<ProductInfo> selectProductInfoByProductSaleNum();

    /**
     * 查询更多单品
     * @return
     */
    List<ProductInfo> selectProductInfoBy0Go10();

    /**
     * 查询华为最新单品展示专区
     * @return
     */
    List<ProductInfo> selectProductInfoByHuaWei();

    /**
     * 查询苹果最新单品展示专区
     * @return
     */
    List<ProductInfo> selectProductInfoByIphone();

    /**
     * 查询小米专区最新单品
     * @return
     */
    List<ProductInfo> selectProductInfoByMi();
}