package com.mbp.dao;

import com.mbp.entity.StoreStandard;

public interface StoreStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int deleteByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insert(StoreStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int insertSelective(StoreStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    StoreStandard selectByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKeySelective(StoreStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_standard
     *
     * @mbg.generated Wed Dec 25 17:55:57 CST 2019
     */
    int updateByPrimaryKey(StoreStandard record);
}