package entity;

import java.io.Serializable;
import java.util.Date;

public class PersonInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_id
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.username
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.sex
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.birthday
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.email
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.telephone
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.signature
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.create_time
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_info
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_id
     *
     * @return the value of person_info.person_id
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_id
     *
     * @param personId the value for person_info.person_id
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.username
     *
     * @return the value of person_info.username
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.username
     *
     * @param username the value for person_info.username
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.sex
     *
     * @return the value of person_info.sex
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.sex
     *
     * @param sex the value for person_info.sex
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.birthday
     *
     * @return the value of person_info.birthday
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.birthday
     *
     * @param birthday the value for person_info.birthday
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.email
     *
     * @return the value of person_info.email
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.email
     *
     * @param email the value for person_info.email
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.telephone
     *
     * @return the value of person_info.telephone
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.telephone
     *
     * @param telephone the value for person_info.telephone
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.signature
     *
     * @return the value of person_info.signature
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.signature
     *
     * @param signature the value for person_info.signature
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.create_time
     *
     * @return the value of person_info.create_time
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.create_time
     *
     * @param createTime the value for person_info.create_time
     *
     * @mbg.generated Wed Dec 25 17:27:40 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}